name: "FanShim Controller"
slug: fanshim
version: "1.0.1"
description: "Controla ventoinha FanShim com base na temperatura da CPU"

startup: application
boot: auto

arch:
  - aarch64
  - armv7
  - armhf

devices:
  - /dev/gpiomem

privileged: []

options:
  on_temperature: 60
  off_temperature: 50
  check_interval: 5

schema:
  on_temperature: int
  off_temperature: int
  check_interval: int